In [ ]:
"""
2. Второе задание

Задача регрессии - необходимо сделать посылку с максимальным качеством и подробную тетрадку с решением и ссылкой на посылку отправить на почту

https://www.kaggle.com/c/house-prices-advanced-regression-techniques

"""

In [ ]:
"""
MSSubClass: Identifies the type of dwelling involved in the sale.	

        20	1-STORY 1946 & NEWER ALL STYLES
        30	1-STORY 1945 & OLDER
        40	1-STORY W/FINISHED ATTIC ALL AGES
        45	1-1/2 STORY - UNFINISHED ALL AGES
        50	1-1/2 STORY FINISHED ALL AGES
        60	2-STORY 1946 & NEWER
        70	2-STORY 1945 & OLDER
        75	2-1/2 STORY ALL AGES
        80	SPLIT OR MULTI-LEVEL
        85	SPLIT FOYER
        90	DUPLEX - ALL STYLES AND AGES
       120	1-STORY PUD (Planned Unit Development) - 1946 & NEWER
       150	1-1/2 STORY PUD - ALL AGES
       160	2-STORY PUD - 1946 & NEWER
       180	PUD - MULTILEVEL - INCL SPLIT LEV/FOYER
       190	2 FAMILY CONVERSION - ALL STYLES AND AGES

MSZoning: Identifies the general zoning classification of the sale.
		
       A	Agriculture
       C	Commercial
       FV	Floating Village Residential
       I	Industrial
       RH	Residential High Density
       RL	Residential Low Density
       RP	Residential Low Density Park 
       RM	Residential Medium Density
	
LotFrontage: Linear feet of street connected to property

LotArea: Lot size in square feet

Street: Type of road access to property

       Grvl	Gravel	
       Pave	Paved
       	
Alley: Type of alley access to property

       Grvl	Gravel
       Pave	Paved
       NA 	No alley access
		
LotShape: General shape of property

       Reg	Regular	
       IR1	Slightly irregular
       IR2	Moderately Irregular
       IR3	Irregular
       
LandContour: Flatness of the property

       Lvl	Near Flat/Level	
       Bnk	Banked - Quick and significant rise from street grade to building
       HLS	Hillside - Significant slope from side to side
       Low	Depression
		
Utilities: Type of utilities available
		
       AllPub	All public Utilities (E,G,W,& S)	
       NoSewr	Electricity, Gas, and Water (Septic Tank)
       NoSeWa	Electricity and Gas Only
       ELO	Electricity only	
	
LotConfig: Lot configuration

       Inside	Inside lot
       Corner	Corner lot
       CulDSac	Cul-de-sac
       FR2	Frontage on 2 sides of property
       FR3	Frontage on 3 sides of property
	
LandSlope: Slope of property
		
       Gtl	Gentle slope
       Mod	Moderate Slope	
       Sev	Severe Slope
	
Neighborhood: Physical locations within Ames city limits

       Blmngtn	Bloomington Heights
       Blueste	Bluestem
       BrDale	Briardale
       BrkSide	Brookside
       ClearCr	Clear Creek
       CollgCr	College Creek
       Crawfor	Crawford
       Edwards	Edwards
       Gilbert	Gilbert
       IDOTRR	Iowa DOT and Rail Road
       MeadowV	Meadow Village
       Mitchel	Mitchell
       Names	North Ames
       NoRidge	Northridge
       NPkVill	Northpark Villa
       NridgHt	Northridge Heights
       NWAmes	Northwest Ames
       OldTown	Old Town
       SWISU	South & West of Iowa State University
       Sawyer	Sawyer
       SawyerW	Sawyer West
       Somerst	Somerset
       StoneBr	Stone Brook
       Timber	Timberland
       Veenker	Veenker
			
Condition1: Proximity to various conditions
	
       Artery	Adjacent to arterial street
       Feedr	Adjacent to feeder street	
       Norm	Normal	
       RRNn	Within 200' of North-South Railroad
       RRAn	Adjacent to North-South Railroad
       PosN	Near positive off-site feature--park, greenbelt, etc.
       PosA	Adjacent to postive off-site feature
       RRNe	Within 200' of East-West Railroad
       RRAe	Adjacent to East-West Railroad
	
Condition2: Proximity to various conditions (if more than one is present)
		
       Artery	Adjacent to arterial street
       Feedr	Adjacent to feeder street	
       Norm	Normal	
       RRNn	Within 200' of North-South Railroad
       RRAn	Adjacent to North-South Railroad
       PosN	Near positive off-site feature--park, greenbelt, etc.
       PosA	Adjacent to postive off-site feature
       RRNe	Within 200' of East-West Railroad
       RRAe	Adjacent to East-West Railroad
	
BldgType: Type of dwelling
		
       1Fam	Single-family Detached	
       2FmCon	Two-family Conversion; originally built as one-family dwelling
       Duplx	Duplex
       TwnhsE	Townhouse End Unit
       TwnhsI	Townhouse Inside Unit
	
HouseStyle: Style of dwelling
	
       1Story	One story
       1.5Fin	One and one-half story: 2nd level finished
       1.5Unf	One and one-half story: 2nd level unfinished
       2Story	Two story
       2.5Fin	Two and one-half story: 2nd level finished
       2.5Unf	Two and one-half story: 2nd level unfinished
       SFoyer	Split Foyer
       SLvl	Split Level
	
OverallQual: Rates the overall material and finish of the house

       10	Very Excellent
       9	Excellent
       8	Very Good
       7	Good
       6	Above Average
       5	Average
       4	Below Average
       3	Fair
       2	Poor
       1	Very Poor
	
OverallCond: Rates the overall condition of the house

       10	Very Excellent
       9	Excellent
       8	Very Good
       7	Good
       6	Above Average	
       5	Average
       4	Below Average	
       3	Fair
       2	Poor
       1	Very Poor
		
YearBuilt: Original construction date

YearRemodAdd: Remodel date (same as construction date if no remodeling or additions)

RoofStyle: Type of roof

       Flat	Flat
       Gable	Gable
       Gambrel	Gabrel (Barn)
       Hip	Hip
       Mansard	Mansard
       Shed	Shed
		
RoofMatl: Roof material

       ClyTile	Clay or Tile
       CompShg	Standard (Composite) Shingle
       Membran	Membrane
       Metal	Metal
       Roll	Roll
       Tar&Grv	Gravel & Tar
       WdShake	Wood Shakes
       WdShngl	Wood Shingles
		
Exterior1st: Exterior covering on house

       AsbShng	Asbestos Shingles
       AsphShn	Asphalt Shingles
       BrkComm	Brick Common
       BrkFace	Brick Face
       CBlock	Cinder Block
       CemntBd	Cement Board
       HdBoard	Hard Board
       ImStucc	Imitation Stucco
       MetalSd	Metal Siding
       Other	Other
       Plywood	Plywood
       PreCast	PreCast	
       Stone	Stone
       Stucco	Stucco
       VinylSd	Vinyl Siding
       Wd Sdng	Wood Siding
       WdShing	Wood Shingles
	
Exterior2nd: Exterior covering on house (if more than one material)

       AsbShng	Asbestos Shingles
       AsphShn	Asphalt Shingles
       BrkComm	Brick Common
       BrkFace	Brick Face
       CBlock	Cinder Block
       CemntBd	Cement Board
       HdBoard	Hard Board
       ImStucc	Imitation Stucco
       MetalSd	Metal Siding
       Other	Other
       Plywood	Plywood
       PreCast	PreCast
       Stone	Stone
       Stucco	Stucco
       VinylSd	Vinyl Siding
       Wd Sdng	Wood Siding
       WdShing	Wood Shingles
	
MasVnrType: Masonry veneer type

       BrkCmn	Brick Common
       BrkFace	Brick Face
       CBlock	Cinder Block
       None	None
       Stone	Stone
	
MasVnrArea: Masonry veneer area in square feet

ExterQual: Evaluates the quality of the material on the exterior 
		
       Ex	Excellent
       Gd	Good
       TA	Average/Typical
       Fa	Fair
       Po	Poor
		
ExterCond: Evaluates the present condition of the material on the exterior
		
       Ex	Excellent
       Gd	Good
       TA	Average/Typical
       Fa	Fair
       Po	Poor
		
Foundation: Type of foundation
		
       BrkTil	Brick & Tile
       CBlock	Cinder Block
       PConc	Poured Contrete	
       Slab	Slab
       Stone	Stone
       Wood	Wood
		
BsmtQual: Evaluates the height of the basement

       Ex	Excellent (100+ inches)	
       Gd	Good (90-99 inches)
       TA	Typical (80-89 inches)
       Fa	Fair (70-79 inches)
       Po	Poor (<70 inches
       NA	No Basement
		
BsmtCond: Evaluates the general condition of the basement

       Ex	Excellent
       Gd	Good
       TA	Typical - slight dampness allowed
       Fa	Fair - dampness or some cracking or settling
       Po	Poor - Severe cracking, settling, or wetness
       NA	No Basement
	
BsmtExposure: Refers to walkout or garden level walls

       Gd	Good Exposure
       Av	Average Exposure (split levels or foyers typically score average or above)	
       Mn	Mimimum Exposure
       No	No Exposure
       NA	No Basement
	
BsmtFinType1: Rating of basement finished area

       GLQ	Good Living Quarters
       ALQ	Average Living Quarters
       BLQ	Below Average Living Quarters	
       Rec	Average Rec Room
       LwQ	Low Quality
       Unf	Unfinshed
       NA	No Basement
		
BsmtFinSF1: Type 1 finished square feet

BsmtFinType2: Rating of basement finished area (if multiple types)

       GLQ	Good Living Quarters
       ALQ	Average Living Quarters
       BLQ	Below Average Living Quarters	
       Rec	Average Rec Room
       LwQ	Low Quality
       Unf	Unfinshed
       NA	No Basement

BsmtFinSF2: Type 2 finished square feet

BsmtUnfSF: Unfinished square feet of basement area

TotalBsmtSF: Total square feet of basement area

Heating: Type of heating
		
       Floor	Floor Furnace
       GasA	Gas forced warm air furnace
       GasW	Gas hot water or steam heat
       Grav	Gravity furnace	
       OthW	Hot water or steam heat other than gas
       Wall	Wall furnace
		
HeatingQC: Heating quality and condition

       Ex	Excellent
       Gd	Good
       TA	Average/Typical
       Fa	Fair
       Po	Poor
		
CentralAir: Central air conditioning

       N	No
       Y	Yes
		
Electrical: Electrical system

       SBrkr	Standard Circuit Breakers & Romex
       FuseA	Fuse Box over 60 AMP and all Romex wiring (Average)	
       FuseF	60 AMP Fuse Box and mostly Romex wiring (Fair)
       FuseP	60 AMP Fuse Box and mostly knob & tube wiring (poor)
       Mix	Mixed
		
1stFlrSF: First Floor square feet
 
2ndFlrSF: Second floor square feet

LowQualFinSF: Low quality finished square feet (all floors)

GrLivArea: Above grade (ground) living area square feet

BsmtFullBath: Basement full bathrooms

BsmtHalfBath: Basement half bathrooms

FullBath: Full bathrooms above grade

HalfBath: Half baths above grade

Bedroom: Bedrooms above grade (does NOT include basement bedrooms)

Kitchen: Kitchens above grade

KitchenQual: Kitchen quality

       Ex	Excellent
       Gd	Good
       TA	Typical/Average
       Fa	Fair
       Po	Poor
       	
TotRmsAbvGrd: Total rooms above grade (does not include bathrooms)

Functional: Home functionality (Assume typical unless deductions are warranted)

       Typ	Typical Functionality
       Min1	Minor Deductions 1
       Min2	Minor Deductions 2
       Mod	Moderate Deductions
       Maj1	Major Deductions 1
       Maj2	Major Deductions 2
       Sev	Severely Damaged
       Sal	Salvage only
		
Fireplaces: Number of fireplaces

FireplaceQu: Fireplace quality

       Ex	Excellent - Exceptional Masonry Fireplace
       Gd	Good - Masonry Fireplace in main level
       TA	Average - Prefabricated Fireplace in main living area or Masonry Fireplace in basement
       Fa	Fair - Prefabricated Fireplace in basement
       Po	Poor - Ben Franklin Stove
       NA	No Fireplace
		
GarageType: Garage location
		
       2Types	More than one type of garage
       Attchd	Attached to home
       Basment	Basement Garage
       BuiltIn	Built-In (Garage part of house - typically has room above garage)
       CarPort	Car Port
       Detchd	Detached from home
       NA	No Garage
		
GarageYrBlt: Year garage was built
		
GarageFinish: Interior finish of the garage

       Fin	Finished
       RFn	Rough Finished	
       Unf	Unfinished
       NA	No Garage
		
GarageCars: Size of garage in car capacity

GarageArea: Size of garage in square feet

GarageQual: Garage quality

       Ex	Excellent
       Gd	Good
       TA	Typical/Average
       Fa	Fair
       Po	Poor
       NA	No Garage
		
GarageCond: Garage condition

       Ex	Excellent
       Gd	Good
       TA	Typical/Average
       Fa	Fair
       Po	Poor
       NA	No Garage
		
PavedDrive: Paved driveway

       Y	Paved 
       P	Partial Pavement
       N	Dirt/Gravel
		
WoodDeckSF: Wood deck area in square feet

OpenPorchSF: Open porch area in square feet

EnclosedPorch: Enclosed porch area in square feet

3SsnPorch: Three season porch area in square feet

ScreenPorch: Screen porch area in square feet

PoolArea: Pool area in square feet

PoolQC: Pool quality
		
       Ex	Excellent
       Gd	Good
       TA	Average/Typical
       Fa	Fair
       NA	No Pool
		
Fence: Fence quality
		
       GdPrv	Good Privacy
       MnPrv	Minimum Privacy
       GdWo	Good Wood
       MnWw	Minimum Wood/Wire
       NA	No Fence
	
MiscFeature: Miscellaneous feature not covered in other categories
		
       Elev	Elevator
       Gar2	2nd Garage (if not described in garage section)
       Othr	Other
       Shed	Shed (over 100 SF)
       TenC	Tennis Court
       NA	None
		
MiscVal: $Value of miscellaneous feature

MoSold: Month Sold (MM)

YrSold: Year Sold (YYYY)

SaleType: Type of sale
		
       WD 	Warranty Deed - Conventional
       CWD	Warranty Deed - Cash
       VWD	Warranty Deed - VA Loan
       New	Home just constructed and sold
       COD	Court Officer Deed/Estate
       Con	Contract 15% Down payment regular terms
       ConLw	Contract Low Down payment and low interest
       ConLI	Contract Low Interest
       ConLD	Contract Low Down
       Oth	Other
		
SaleCondition: Condition of sale

       Normal	Normal Sale
       Abnorml	Abnormal Sale -  trade, foreclosure, short sale
       AdjLand	Adjoining Land Purchase
       Alloca	Allocation - two linked properties with separate deeds, typically condo with a garage unit	
       Family	Sale between family members
       Partial	Home was not completed when last assessed (associated with New Homes)"""

In [79]:
from __future__ import division, print_function
# отключим всякие предупреждения Anaconda
import warnings
warnings.filterwarnings('ignore')
%pylab inline
import seaborn as sns
figsize(12, 8)
import pandas as pd
import sys
from sklearn.preprocessing import LabelEncoder
from sklearn.cross_validation import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.grid_search import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, classification_report

Populating the interactive namespace from numpy and matplotlib

In [80]:
train = pd.read_csv('train_houses.csv')
test = pd.read_csv('test_houses.csv')

In [81]:
train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [82]:
test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [83]:
train.Alley.value_counts()

Grvl    50
Pave    41
Name: Alley, dtype: int64

In [84]:
len(train)

1460

In [85]:
train = train.drop('Alley', axis=1)

In [86]:
test = test.drop('Alley', axis=1)

In [87]:
train.PoolQC.value_counts()

Gd    3
Ex    2
Fa    2
Name: PoolQC, dtype: int64

In [88]:
train.PoolQC.isnull().sum()

1453

In [89]:
train = train.drop('PoolQC', axis=1)

In [90]:
test = test.drop('PoolQC', axis=1)

In [91]:
train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,0,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,0,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,0,0,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,0,NaN,NaN,0,12,2008,WD,Normal,250000

In [92]:
train.Fence.isnull().sum()

1179

In [93]:
train.MiscFeature.isnull().sum()

1406

In [94]:
train = train.drop('Fence', axis=1)
train = train.drop('MiscFeature', axis=1)
test = test.drop('Fence', axis=1)
test = test.drop('MiscFeature', axis=1)

In [95]:
train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,0,0,0,0,12,2008,WD,Normal,250000

In [96]:
train.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
Street             0
LotShape           0
LandContour        0
Utilities          0
LotConfig          0
LandSlope          0
Neighborhood       0
Condition1         0
Condition2         0
BldgType           0
HouseStyle         0
OverallQual        0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
RoofStyle          0
RoofMatl           0
Exterior1st        0
Exterior2nd        0
MasVnrType         8
MasVnrArea         8
ExterQual          0
ExterCond          0
Foundation         0
BsmtQual          37
                ...
BsmtHalfBath       0
FullBath           0
HalfBath           0
BedroomAbvGr       0
KitchenAbvGr       0
KitchenQual        0
TotRmsAbvGrd       0
Functional         0
Fireplaces         0
FireplaceQu      690
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageCars         0
GarageArea         0
GarageQual        81
GarageCond        81
PavedDrive         0
WoodDeckSF         0
OpenPorchSF        0
EnclosedPorch      0
3SsnPorch          0
ScreenPorch        0
PoolArea           0
MiscVal            0
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 77, dtype: int64

In [97]:
train.loc[:, train.isnull().any()]

,LotFrontage,MasVnrType,MasVnrArea,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,Electrical,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageQual,GarageCond
0,65.0,BrkFace,196.0,Gd,TA,No,GLQ,Unf,SBrkr,NaN,Attchd,2003.0,RFn,TA,TA
1,80.0,None,0.0,Gd,TA,Gd,ALQ,Unf,SBrkr,TA,Attchd,1976.0,RFn,TA,TA
2,68.0,BrkFace,162.0,Gd,TA,Mn,GLQ,Unf,SBrkr,TA,Attchd,2001.0,RFn,TA,TA
3,60.0,None,0.0,TA,Gd,No,ALQ,Unf,SBrkr,Gd,Detchd,1998.0,Unf,TA,TA
4,84.0,BrkFace,350.0,Gd,TA,Av,GLQ,Unf,SBrkr,TA,Attchd,2000.0,RFn,TA,TA
5,85.0,None,0.0,Gd,TA,No,GLQ,Unf,SBrkr,NaN,Attchd,1993.0,Unf,TA,TA
6,75.0,Stone,186.0,Ex,TA,Av,GLQ,Unf,SBrkr,Gd,Attchd,2004.0,RFn,TA,TA
7,NaN,Stone,240.0,Gd,TA,Mn,ALQ,BLQ,SBrkr,TA,Attchd,1973.0,RFn,TA,TA
8,51.0,None,0.0,TA,TA,No,Unf,Unf,FuseF,TA,Detchd,1931.0,Unf,Fa,TA
9,50.0,None,0.0,TA,TA,No,GLQ,Unf,SBrkr,TA,Attchd,1939.0,RFn,Gd,TA
10,70.0,None,0.0,TA,TA,No,Rec,Unf,SBrkr,NaN,Detchd,1965.0,Unf,TA,TA
11,85.0,Stone,286.0,Ex,TA,No,GLQ,Unf,SBrkr,Gd,BuiltIn,2005.0,Fin,TA,TA
12,NaN,None,0.0,TA,TA,No,ALQ,Unf,SBrkr,NaN,Detchd,1962.0,Unf,TA,TA
13,91.0,Stone,306.0,Gd,TA,Av,Unf,Unf,SBrkr,Gd,Attchd,2006.0,RFn,TA,TA
14,NaN,BrkFace,212.0,TA,TA,No,BLQ,Unf,SBrkr,Fa,Attchd,1960.0,RFn,TA,TA
15,51.0,None,0.0,TA,TA,No,Unf,Unf,FuseA,NaN,Detchd,1991.0,Unf,TA,TA
16,NaN,BrkFace,180.0,TA,TA,No,ALQ,Unf,SBrkr,TA,Attchd,1970.0,Fin,TA,TA
17,72.0,None,0.0,NaN,NaN,NaN,NaN,NaN,SBrkr,NaN,CarPort,1967.0,Unf,TA,TA
18,66.0,None,0.0,TA,TA,No,GLQ,Unf,SBrkr,NaN,Detchd,2004.0,Unf,TA,TA
19,70.0,None,0.0,TA,TA,No,LwQ,Unf,SBrkr,NaN,Attchd,1958.0,Unf,TA,TA
20,101.0,BrkFace,380.0,Ex,TA,Av,Unf,Unf,SBrkr,Gd,BuiltIn,2005.0,RFn,TA,TA
21,57.0,None,0.0,TA,TA,No,Unf,Unf,FuseF,Gd,Attchd,1930.0,Unf,TA,TA
22,75.0,BrkFace,281.0,Gd,TA,No,Unf,Unf,SBrkr,Gd,Attchd,2002.0,RFn,TA,TA
23,44.0,None,0.0,Gd,TA,No,GLQ,Unf,SBrkr,TA,Attchd,1976.0,Unf,TA,TA
24,NaN,None,0.0,TA,TA,Mn,Rec,ALQ,SBrkr,TA,Attchd,1968.0,Unf,TA,TA
25,110.0,Stone,640.0,Gd,TA,No,Unf,Unf,SBrkr,Gd,Attchd,2007.0,RFn,TA,TA
26,60.0,None,0.0,TA,TA,Mn,BLQ,Rec,SBrkr,NaN,Detchd,2005.0,Unf,TA,TA
27,98.0,Stone,200.0,Ex,TA,No,GLQ,Unf,SBrkr,Gd,Attchd,2008.0,RFn,TA,TA
28,47.0,None,0.0,TA,TA,Gd,BLQ,Unf,SBrkr,Gd,Attchd,1957.0,RFn,TA,TA
29,60.0,None,0.0,TA,TA,No,Unf,Unf,SBrkr,NaN,Detchd,1920.0,Unf,Fa,TA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,60.0,None,0.0,Gd,Gd,Av,Unf,Unf,SBrkr,Gd,BuiltIn,2005.0,Fin,TA,TA
1431,NaN,None,0.0,Gd,TA,No,LwQ,Unf,SBrkr,NaN,Attchd,1976.0,RFn,TA,TA
1432,60.0,None,0.0,TA,TA,No,Unf,Unf,SBrkr,NaN,Detchd,1928.0,Unf,Fa,Fa
1433,93.0,BrkFace,318.0,Gd,TA,No,Unf,Unf,SBrkr,TA,Attchd,2000.0,Fin,TA,TA
1434,80.0,None,0.0,TA,TA,No,ALQ,Unf,SBrkr,Gd,Attchd,1977.0,RFn,TA,TA
1435,80.0,BrkFace,237.0,TA,TA,No,Unf,Unf,SBrkr,Gd,Attchd,1962.0,RFn,TA,TA
1436,60.0,None,0.0,TA,TA,No,ALQ,Unf,SBrkr,NaN,Detchd,1974.0,Unf,TA,TA
1437,96.0,Stone,426.0,Ex,TA,Av,GLQ,Unf,SBrkr,Gd,Attchd,2008.0,Fin,TA,TA
1438,90.0,None,0.0,TA,TA,No,GLQ,Unf,FuseA,NaN,Attchd,1957.0,Unf,TA,TA
1439,80.0,BrkFace,96.0,TA,TA,No,GLQ,Rec,SBrkr,TA,Attchd,1979.0,RFn,TA,TA
1440,79.0,None,0.0,Ex,TA,No,Unf,Unf,SBrkr,Gd,Detchd,1993.0,Fin,TA,TA
1441,NaN,BrkFace,147.0,Gd,TA,Av,GLQ,Unf,SBrkr,TA,Attchd,2004.0,RFn,TA,TA
1442,85.0,Stone,160.0,Ex,TA,Av,GLQ,Unf,SBrkr,Ex,Attchd,2008.0,Fin,TA,TA
1443,NaN,None,0.0,TA,TA,No,Unf,Unf,FuseF,Gd,Detchd,1916.0,Unf,Fa,Po
1444,63.0,BrkFace,106.0,Gd,TA,Av,Unf,Unf,SBrkr,NaN,Attchd,2004.0,RFn,TA,TA
1445,70.0,None,0.0,TA,TA,Gd,LwQ,Rec,SBrkr,NaN,Detchd,1990.0,Unf,TA,TA
1446,NaN,BrkFace,189.0,TA,TA,No,Rec,Unf,SBrkr,NaN,Attchd,1962.0,Unf,TA,TA
1447,80.0,BrkFace,438.0,Gd,TA,No,GLQ,Unf,SBrkr,TA,Attchd,1995.0,RFn,TA,TA
1448,70.0,None,0.0,Fa,TA,No,Unf,Unf,SBrkr,NaN,Detchd,1950.0,Unf,Fa,TA
1449,21.0,None,0.0,Gd,TA,Av,GLQ,Unf,SBrkr,NaN,NaN,NaN,NaN,NaN,NaN
1450,60.0,None,0.0,Gd,TA,No,Unf,Unf,SBrkr,NaN,NaN,NaN,NaN,NaN,NaN
1451,78.0,Stone,194.0,Gd,TA,No,Unf,Unf,SBrkr,Gd,Attchd,2008.0,Fin,TA,TA
1452,35.0,BrkFace,80.0,Gd,TA,Gd,GLQ,Unf,SBrkr,NaN,Basment,2005.0,Fin,TA,TA
1453,90.0,None,0.0,Gd,TA,No,Unf,Unf,SBrkr,NaN,NaN,NaN,NaN,NaN,NaN
1454,62.0,None,0.0,Gd,TA,No,GLQ,Unf,SBrkr,NaN,Attchd,2004.0,RFn,TA,TA
1455,62.0,None,0.0,Gd,TA,No,Unf,Unf,SBrkr,TA,Attchd,1999.0,RFn,TA,TA
1456,85.0,Stone,119.0,Gd,TA,No,ALQ,Rec,SBrkr,TA,Attchd,1978.0,Unf,TA,TA
1457,66.0,None,0.0,TA,Gd,No,GLQ,Unf,SBrkr,Gd,Attchd,1941.0,RFn,TA,TA
1458,68.0,None,0.0,TA,TA,Mn,GLQ,Rec,FuseA,NaN,Attchd,1950.0,Unf,TA,TA
1459,75.0,None,0.0,TA,TA,No,BLQ,LwQ,SBrkr,NaN,Attchd,1965.0,Fin,TA,TA

In [98]:
train.LotFrontage.isnull().sum()

259

In [99]:
train.LotFrontage.mean()

70.04995836802665

In [100]:
train.LotFrontage.median()

69.0

In [101]:
train.LotFrontage.std()

24.284751774483183

In [102]:
train.LotFrontage.min()

21.0

In [103]:
train.LotFrontage.max()

313.0

In [104]:
train.LotFrontage = train.LotFrontage.fillna(value=train.LotFrontage.mean())

In [105]:
train.LotFrontage.isnull().sum()

0

In [106]:
test.LotFrontage = test.LotFrontage.fillna(value=test.LotFrontage.mean())

In [112]:
train.loc[:, train.isnull().any()].head()

,MasVnrType,MasVnrArea,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,Electrical,GarageType,GarageYrBlt,GarageFinish,GarageQual,GarageCond
0,BrkFace,196.0,Gd,TA,No,GLQ,Unf,SBrkr,Attchd,2003.0,RFn,TA,TA
1,None,0.0,Gd,TA,Gd,ALQ,Unf,SBrkr,Attchd,1976.0,RFn,TA,TA
2,BrkFace,162.0,Gd,TA,Mn,GLQ,Unf,SBrkr,Attchd,2001.0,RFn,TA,TA
3,None,0.0,TA,Gd,No,ALQ,Unf,SBrkr,Detchd,1998.0,Unf,TA,TA
4,BrkFace,350.0,Gd,TA,Av,GLQ,Unf,SBrkr,Attchd,2000.0,RFn,TA,TA

In [113]:
def del_Nan_columns(df):
    for column in list(df):
        if df[column].isnull().sum()/len(df) > 0.3:
            print(column)
            df = df.drop(column, axis=1)
    return df

In [114]:
train = del_Nan_columns(train)

In [115]:
train.loc[:, train.isnull().any()].head()

,MasVnrType,MasVnrArea,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,Electrical,GarageType,GarageYrBlt,GarageFinish,GarageQual,GarageCond
0,BrkFace,196.0,Gd,TA,No,GLQ,Unf,SBrkr,Attchd,2003.0,RFn,TA,TA
1,None,0.0,Gd,TA,Gd,ALQ,Unf,SBrkr,Attchd,1976.0,RFn,TA,TA
2,BrkFace,162.0,Gd,TA,Mn,GLQ,Unf,SBrkr,Attchd,2001.0,RFn,TA,TA
3,None,0.0,TA,Gd,No,ALQ,Unf,SBrkr,Detchd,1998.0,Unf,TA,TA
4,BrkFace,350.0,Gd,TA,Av,GLQ,Unf,SBrkr,Attchd,2000.0,RFn,TA,TA

In [118]:
train.MasVnrType = train.MasVnrType.fillna('None')

In [120]:
test = test.drop('FireplaceQu', axis=1)

In [121]:
test.MasVnrType = test.MasVnrType.fillna('None')

In [122]:
train.loc[:, train.isnull().any()].head()

,MasVnrArea,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,Electrical,GarageType,GarageYrBlt,GarageFinish,GarageQual,GarageCond
0,196.0,Gd,TA,No,GLQ,Unf,SBrkr,Attchd,2003.0,RFn,TA,TA
1,0.0,Gd,TA,Gd,ALQ,Unf,SBrkr,Attchd,1976.0,RFn,TA,TA
2,162.0,Gd,TA,Mn,GLQ,Unf,SBrkr,Attchd,2001.0,RFn,TA,TA
3,0.0,TA,Gd,No,ALQ,Unf,SBrkr,Detchd,1998.0,Unf,TA,TA
4,350.0,Gd,TA,Av,GLQ,Unf,SBrkr,Attchd,2000.0,RFn,TA,TA

In [124]:
train.MasVnrArea.isnull().sum()

8

In [125]:
train.MasVnrArea = train.MasVnrArea.fillna(train.MasVnrArea.mean())

In [126]:
test.MasVnrArea = test.MasVnrArea.fillna(test.MasVnrArea.mean())

In [127]:
train.BsmtQual.isnull().sum()

37

In [128]:
train.BsmtQual.value_counts()

TA    649
Gd    618
Ex    121
Fa     35
Name: BsmtQual, dtype: int64

In [129]:
train.BsmtQual = train.BsmtQual.fillna('TA')

In [130]:
test.BsmtQual = test.BsmtQual.fillna('TA')

In [131]:
train.loc[:, train.isnull().any()].head()

,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,Electrical,GarageType,GarageYrBlt,GarageFinish,GarageQual,GarageCond
0,TA,No,GLQ,Unf,SBrkr,Attchd,2003.0,RFn,TA,TA
1,TA,Gd,ALQ,Unf,SBrkr,Attchd,1976.0,RFn,TA,TA
2,TA,Mn,GLQ,Unf,SBrkr,Attchd,2001.0,RFn,TA,TA
3,Gd,No,ALQ,Unf,SBrkr,Detchd,1998.0,Unf,TA,TA
4,TA,Av,GLQ,Unf,SBrkr,Attchd,2000.0,RFn,TA,TA

In [132]:
train.BsmtCond.isnull().sum()

37

In [133]:
train.BsmtCond.value_counts()

TA    1311
Gd      65
Fa      45
Po       2
Name: BsmtCond, dtype: int64

In [134]:
train.BsmtCond = train.BsmtCond.fillna('TA')

In [135]:
test.BsmtCond = test.BsmtCond.fillna('TA')

In [136]:
train.BsmtExposure.isnull().sum()

38

In [137]:
test.BsmtExposure.isnull().sum()

44

In [138]:
train.BsmtExposure.value_counts()

No    953
Av    221
Gd    134
Mn    114
Name: BsmtExposure, dtype: int64

In [139]:
train.BsmtExposure = train.BsmtExposure.fillna('No')

In [140]:
test.BsmtExposure = test.BsmtExposure.fillna('No')

In [141]:
train.loc[:, train.isnull().any()].head()

,BsmtFinType1,BsmtFinType2,Electrical,GarageType,GarageYrBlt,GarageFinish,GarageQual,GarageCond
0,GLQ,Unf,SBrkr,Attchd,2003.0,RFn,TA,TA
1,ALQ,Unf,SBrkr,Attchd,1976.0,RFn,TA,TA
2,GLQ,Unf,SBrkr,Attchd,2001.0,RFn,TA,TA
3,ALQ,Unf,SBrkr,Detchd,1998.0,Unf,TA,TA
4,GLQ,Unf,SBrkr,Attchd,2000.0,RFn,TA,TA

In [142]:
train.BsmtFinType1.isnull().sum()

37

In [143]:
train.BsmtFinType1.value_counts()

Unf    430
GLQ    418
ALQ    220
BLQ    148
Rec    133
LwQ     74
Name: BsmtFinType1, dtype: int64

In [144]:
train.BsmtFinType1 = train.BsmtFinType1.fillna('Unf')

In [145]:
test.BsmtFinType1 = test.BsmtFinType1.fillna('Unf')

In [146]:
train.BsmtFinType2.isnull().sum()

38

In [147]:
train.BsmtFinType2 = train.BsmtFinType2.fillna('Unf')

In [148]:
test.BsmtFinType2 = test.BsmtFinType2.fillna('Unf')

In [149]:
train.Electrical.isnull().sum()

1

In [150]:
train.Electrical.value_counts()

SBrkr    1334
FuseA      94
FuseF      27
FuseP       3
Mix         1
Name: Electrical, dtype: int64

In [151]:
train.Electrical = train.Electrical.fillna('SBrkr')

In [152]:
test.Electrical = test.Electrical.fillna('SBrkr')

In [153]:
train.loc[:, train.isnull().any()].head()

  GarageType  GarageYrBlt GarageFinish GarageQual GarageCond
0     Attchd       2003.0          RFn         TA         TA
1     Attchd       1976.0          RFn         TA         TA
2     Attchd       2001.0          RFn         TA         TA
3     Detchd       1998.0          Unf         TA         TA
4     Attchd       2000.0          RFn         TA         TA

In [155]:
train.GarageType.isnull().sum()

81

In [156]:
train.GarageType.value_counts()

Attchd     870
Detchd     387
BuiltIn     88
Basment     19
CarPort      9
2Types       6
Name: GarageType, dtype: int64

In [157]:
train.GarageType = train.GarageType.fillna('Attchd')

In [158]:
test.GarageType = test.GarageType.fillna('Attchd')

In [159]:
train.GarageYrBlt.isnull().sum()

81

In [161]:
train.GarageYrBlt = train.GarageYrBlt.fillna(train.GarageYrBlt.mean())

In [162]:
test.GarageYrBlt = test.GarageYrBlt.fillna(test.GarageYrBlt.mean())

In [163]:
train.GarageFinish.isnull().sum()

81

In [164]:
train.GarageFinish.value_counts()

Unf    605
RFn    422
Fin    352
Name: GarageFinish, dtype: int64

In [165]:
train.GarageFinish = train.GarageFinish.fillna('Unf')

In [166]:
test.GarageFinish = test.GarageFinish.fillna('Unf')

In [167]:
train.loc[:, train.isnull().any()].head()

  GarageQual GarageCond
0         TA         TA
1         TA         TA
2         TA         TA
3         TA         TA
4         TA         TA

In [168]:
train.GarageQual.isnull().sum()

81

In [169]:
train.GarageQual.value_counts()

TA    1311
Fa      48
Gd      14
Po       3
Ex       3
Name: GarageQual, dtype: int64

In [170]:
train.GarageQual = train.GarageQual.fillna('TA')

In [171]:
test.GarageQual = test.GarageQual.fillna('TA')

In [172]:
train.GarageCond = train.GarageCond.fillna('TA')

In [173]:
test.GarageCond = test.GarageCond.fillna('TA')

In [174]:
train.loc[:, train.isnull().any()].head()

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [186]:
encoder = LabelEncoder()

for column in train.select_dtypes(include=['object']).columns:
    train[column] = encoder.fit_transform(train[column])

In [187]:
train.select_dtypes(include=['object']).columns

Index([], dtype='object')

In [188]:
from sklearn.ensemble import RandomForestRegressor

In [189]:
X_train = train.loc[:, train.columns != 'SalePrice']

In [190]:
Y_train = train['SalePrice']

In [ ]:
params_rf = {'n_estimators': [x for x in range(10,250,10)]}

rf = GridSearchCV(estimator=RandomForestRegressor(), param_grid=params_rf, n_jobs=-1, cv=5)
rf.fit(X_train, Y_train)

In [192]:
print('\n',rf.best_estimator_)

 RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=190, n_jobs=1, oob_score=False, random_state=None,
           verbose=0, warm_start=False)

In [195]:
score = cross_val_score(rf.best_estimator_, X_train, Y_train, cv=5, n_jobs=-1)

In [197]:
print(score.mean())

0.859184998686

In [200]:
test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,120,0,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,Corner,...,36,0,0,0,0,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,IR1,Lvl,AllPub,Inside,...,34,0,0,0,0,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,IR1,Lvl,AllPub,Inside,...,36,0,0,0,0,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,IR1,HLS,AllPub,Inside,...,82,0,0,144,0,0,1,2010,WD,Normal

In [208]:

test.MSZoning.value_counts()

RL         1114
RM          242
FV           74
C (all)      15
RH           10
Name: MSZoning, dtype: int64

In [209]:
train.MSZoning.value_counts()

3    1151
4     218
1      65
2      16
0      10
Name: MSZoning, dtype: int64

In [250]:

for column in test.select_dtypes(include=['object']).columns:
    print(column)
    test[column] = encoder.fit_transform(test[column])

In [212]:
test.MSZoning.value_counts()

RL         1114
RM          242
FV           74
C (all)      15
RH           10
Name: MSZoning, dtype: int64

In [213]:
test.MSZoning = test.MSZoning.fillna('RL')

In [217]:
test.loc[:, test.isnull().any()].columns

Index(['Utilities', 'Exterior1st', 'Exterior2nd', 'BsmtFinSF1', 'BsmtFinSF2',
       'BsmtUnfSF', 'TotalBsmtSF', 'BsmtFullBath', 'BsmtHalfBath',
       'KitchenQual', 'Functional', 'GarageCars', 'GarageArea', 'SaleType'],
      dtype='object')

In [223]:
for col in test.loc[:, test.isnull().any()].columns:
    if col in test.select_dtypes(include=['int64']).columns:
        test[col] = test[col].fillna(test[col].mean())

In [227]:
test.loc[:, test.isnull().any()].columns

Index(['Utilities', 'Exterior1st', 'Exterior2nd', 'BsmtFinSF1', 'BsmtFinSF2',
       'BsmtUnfSF', 'TotalBsmtSF', 'BsmtFullBath', 'BsmtHalfBath',
       'KitchenQual', 'Functional', 'GarageCars', 'GarageArea', 'SaleType'],
      dtype='object')

In [230]:
len(test.loc[:, test.isnull().any()].columns)

14

In [231]:
test.Utilities.value_counts()

AllPub    1457
Name: Utilities, dtype: int64

In [232]:
test.Utilities = test.Utilities.fillna('AllPub')

In [233]:
test.Exterior1st.value_counts()

VinylSd    510
MetalSd    230
HdBoard    220
Wd Sdng    205
Plywood    113
CemntBd     65
BrkFace     37
WdShing     30
AsbShng     24
Stucco      18
BrkComm      4
AsphShn      1
CBlock       1
Name: Exterior1st, dtype: int64

In [234]:
test.Exterior1st = test.Exterior1st.fillna('VinylSd')

In [236]:
test.Exterior2nd = test.Exterior2nd.fillna('VinylSd')

In [239]:
test.loc[:, test.isnull().any()].head()

,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,BsmtFullBath,BsmtHalfBath,KitchenQual,Functional,GarageCars,GarageArea,SaleType
0,468.0,144.0,270.0,882.0,0.0,0.0,TA,Typ,1.0,730.0,WD
1,923.0,0.0,406.0,1329.0,0.0,0.0,Gd,Typ,1.0,312.0,WD
2,791.0,0.0,137.0,928.0,0.0,0.0,TA,Typ,2.0,482.0,WD
3,602.0,0.0,324.0,926.0,0.0,0.0,Gd,Typ,2.0,470.0,WD
4,263.0,0.0,1017.0,1280.0,0.0,0.0,Gd,Typ,2.0,506.0,WD

In [240]:
test.KitchenQual.value_counts()

TA    757
Gd    565
Ex    105
Fa     31
Name: KitchenQual, dtype: int64

In [241]:
test.KitchenQual = test.KitchenQual.fillna('TA')

In [242]:
test.Functional.value_counts()

Typ     1357
Min2      36
Min1      34
Mod       20
Maj1       5
Maj2       4
Sev        1
Name: Functional, dtype: int64

In [243]:
test.Functional = test.Functional.fillna('Typ')

In [244]:
test.SaleType.value_counts()

WD       1258
New       117
COD        44
ConLD      17
CWD         8
ConLI       4
Oth         4
Con         3
ConLw       3
Name: SaleType, dtype: int64

In [245]:
test.SaleType = test.SaleType.fillna('WD')

In [246]:
test.loc[:, test.isnull().any()].head()

,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,BsmtFullBath,BsmtHalfBath,GarageCars,GarageArea
0,468.0,144.0,270.0,882.0,0.0,0.0,1.0,730.0
1,923.0,0.0,406.0,1329.0,0.0,0.0,1.0,312.0
2,791.0,0.0,137.0,928.0,0.0,0.0,2.0,482.0
3,602.0,0.0,324.0,926.0,0.0,0.0,2.0,470.0
4,263.0,0.0,1017.0,1280.0,0.0,0.0,2.0,506.0

In [247]:
for col in test.loc[:, test.isnull().any()].columns:
    test[col] = test[col].fillna(test[col].mean())

In [248]:
test.loc[:, test.isnull().any()].head()

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [249]:
for column in test.select_dtypes(include=['object']).columns:
    print(column)
    test[column] = encoder.fit_transform(test[column])

Utilities
LotConfig
LandSlope
Neighborhood
Condition1
Condition2
BldgType
HouseStyle
RoofStyle
RoofMatl
Exterior1st
Exterior2nd
MasVnrType
ExterQual
ExterCond
Foundation
BsmtQual
BsmtCond
BsmtExposure
BsmtFinType1
BsmtFinType2
Heating
HeatingQC
CentralAir
Electrical
KitchenQual
Functional
GarageType
GarageFinish
GarageQual
GarageCond
PavedDrive
SaleType
SaleCondition

In [252]:
predicted = rf.best_estimator_.predict(test)

In [254]:
test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,2,80.0,11622,1,3,3,0,4,...,0,0,0,120,0,0,6,2010,8,4
1,1462,20,3,81.0,14267,1,0,3,0,0,...,36,0,0,0,0,12500,6,2010,8,4
2,1463,60,3,74.0,13830,1,0,3,0,4,...,34,0,0,0,0,0,3,2010,8,4
3,1464,60,3,78.0,9978,1,0,3,0,4,...,36,0,0,0,0,0,6,2010,8,4
4,1465,120,3,43.0,5005,1,0,1,0,4,...,82,0,0,144,0,0,1,2010,8,4

In [255]:
output = pd.DataFrame( data={"id":test["Id"], "SalePrice": predicted })

In [256]:
output.to_csv( "House_price_regression.csv", index=False, quoting=3 )

In [257]:
# Score 0.14778
# 1245/1900
# https://www.kaggle.com/c/house-prices-advanced-regression-techniques/submissions?sortBy=date&group=all&page=1